### PR TITLE
update

### PR DESCRIPTION
**Pull request by Linnnnnna**
are you sure [[bundle.properties](https://github.com/StormyBytes/mindustry-client/commit/2e8787b3d3f065b509f6104adf1e8627f345caaf#diff-5e346bcec4e8e1d545e035b1e438472bc51937398ac3e8e81308605ec82aea2c)](https://github.com/StormyBytes/mindustry-client/commit/2e8787b3d3f065b509f6104adf1e8627f345caaf) ?

### CODE REVIEW

**Comment by sbxte** [comment]
uh you have a merge conflict

**Comment by Linnnnnna** [comment]
> uh you have a merge conflict
D%NL_WMT%G5APPUY}QMK2Y7


[[bundle.properties](https://github.com/StormyBytes/mindustry-client/commit/2e8787b3d3f065b509f6104adf1e8627f345caaf#diff-5e346bcec4e8e1d545e035b1e438472bc51937398ac3e8e81308605ec82aea2c)](https://github.com/StormyBytes/mindustry-client/commit/2e8787b3d3f065b509f6104adf1e8627f345caaf)

**Comment by sbxte** [comment]
yeah that is a merge conflict

**Comment by Linnnnnna** [comment]
> 

is this ok?

**Comment by Linnnnnna** [comment]
> yeah that is a merge conflict

is this ok?

**Pull request merged**
